"""Rector and Fractor, one rule at a time.

A campaign is one tool with one configuration on one branch, for example
"flight-rector". `plan` asks the tool (dry run, JSON) which rules would change
which files. `apply` runs exactly one rule. The result is reviewed, measured and
committed on its own, so every commit on the branch is one rule and one reason.
Because rules interact, `plan` is re-run after every commit until nothing is
pending.
"""

from __future__ import annotations

import re
from pathlib import Path

from .core import Flight, die, extract_json, git, git_dirty, git_head, now, sh, short_class

TOOLS = ('rector', 'fractor')
MARKERS = re.compile(r'\b(TODO|FIXME|XXX|@todo)\b', re.I)
LEVEL_CONSTANT = re.compile(r'UP_TO_TYPO3_(\d+)')

RECTOR_TEMPLATE = """<?php

declare(strict_types=1);

use Rector\\Config\\RectorConfig;
use Ssch\\TYPO3Rector\\Set\\Typo3LevelSetList;

return RectorConfig::configure()
    ->withPaths([
{paths}
    ])
    ->withSets([
        Typo3LevelSetList::UP_TO_TYPO3_{level},
    ]);
"""

FRACTOR_TEMPLATE = """<?php

declare(strict_types=1);

use a9f\\Fractor\\Configuration\\FractorConfiguration;
use a9f\\Typo3Fractor\\Set\\Typo3LevelSetList;

return FractorConfiguration::configure()
    ->withPaths([
{paths}
    ])
    ->withSets([
        Typo3LevelSetList::UP_TO_TYPO3_{level},
    ]);
"""

WRAPPER_TEMPLATE = """<?php

declare(strict_types=1);

// Generated by upgrade-pilot: the project configuration with every loaded rule
// skipped except one. Used when the installed Rector has no --only option.

use Rector\\Config\\RectorConfig;

return static function (RectorConfig $rectorConfig): void {{
    $project = require {project};
    $project($rectorConfig);
    $rectorConfig->skip({skip});
}};
"""


def campaign_of(flight: Flight, name: str, create_tool: str | None = None) -> dict:
    campaigns = flight.log.setdefault('campaigns', {})
    if name not in campaigns:
        if not create_tool:
            die(f'unknown campaign {name}. Known: {", ".join(campaigns) or "none"}. Start one with rules plan.')
        campaigns[name] = {'tool': create_tool, 'config': f'{create_tool}.php', 'created': now(), 'plans': [], 'rules': {}}
    return campaigns[name]


def default_campaign(flight: Flight, tool: str | None) -> str:
    phase = flight.log.get('phase', 'preflight')
    return f'{phase}-{tool or "rector"}'


def extension_paths(flight: Flight) -> list[str]:
    paths = []
    for ext in flight.extensions():
        if ext['path'] == '.':
            for candidate in ('Classes', 'Configuration', 'Resources', 'Tests', 'ext_localconf.php', 'ext_tables.php', 'ext_emconf.php'):
                if (flight.root / candidate).exists():
                    paths.append(candidate)
        else:
            paths.append(ext['path'])
    return paths


PHP_TEMPLATE = """<?php

declare(strict_types=1);

use Rector\\Config\\RectorConfig;

// PHP level set, applied as its own campaign, one rule per commit.
return RectorConfig::configure()
    ->withPaths([
{paths}
    ])
    ->withPhpSets({php_flag}: true);
"""


def php_minimum(flight: Flight) -> str | None:
    constraint = flight.config.get('facts', {}).get(flight.config['target'], {}).get('core_php') or ''
    match = re.search(r'(\d+)\.(\d+)', constraint)
    return f'{match.group(1)}.{match.group(2)}' if match else None


def cmd_config(args) -> None:
    flight = Flight.load()
    if args.set == 'php':
        if args.tool != 'rector':
            die('the PHP level set exists for Rector only')
        php = args.php or php_minimum(flight)
        if not php:
            die('no PHP version: pass --php 8.2 or run upgrade-pilot versions first')
        path = flight.root / 'rector-php.php'
        flag = 'php' + php.replace('.', '')
        if path.is_file():
            text = path.read_text(encoding='utf-8')
            path.write_text(re.sub(r'withPhpSets\(php\d+: true\)', f'withPhpSets({flag}: true)', text), encoding='utf-8')
        else:
            paths = '\n'.join(f"        __DIR__ . '/{p}'," for p in extension_paths(flight))
            path.write_text(PHP_TEMPLATE.format(paths=paths, php_flag=flag), encoding='utf-8')
        flight.event(f'rector-php.php at PHP {php}')
        flight.save()
        print(f'rector-php.php written (withPhpSets({flag}: true)). Campaign: rules plan --tool rector --campaign <phase>-rector-php --config rector-php.php')
        return
    if args.level is None:
        die('--level <TYPO3 major> is required for the typo3 set')
    path = flight.root / f'{args.tool}.php'
    level = str(args.level)
    if path.is_file():
        text = path.read_text(encoding='utf-8')
        if not LEVEL_CONSTANT.search(text):
            die(f'{path.name} exists without an UP_TO_TYPO3_<n> level set. Edit it by hand.')
        current = LEVEL_CONSTANT.search(text).group(1)
        if current == level:
            print(f'{path.name}: already at UP_TO_TYPO3_{level}')
            return
        path.write_text(LEVEL_CONSTANT.sub(f'UP_TO_TYPO3_{level}', text), encoding='utf-8')
        flight.event(f'{path.name}: level set raised {current} -> {level}')
        flight.save()
        print(f'{path.name}: UP_TO_TYPO3_{current} -> UP_TO_TYPO3_{level}')
        return
    paths = '\n'.join(f"        __DIR__ . '/{p}'," for p in extension_paths(flight))
    template = RECTOR_TEMPLATE if args.tool == 'rector' else FRACTOR_TEMPLATE
    path.write_text(template.format(paths=paths, level=level), encoding='utf-8')
    flight.event(f'{path.name} created at UP_TO_TYPO3_{level}')
    flight.save()
    print(f'{path.name} written (UP_TO_TYPO3_{level}) for: {", ".join(extension_paths(flight))}')


# -- tool plumbing -------------------------------------------------------------

def base_cmd(flight: Flight, campaign: dict) -> str:
    cmd = f'{flight.tool(campaign["tool"])} process --output-format=json --no-progress-bar --clear-cache'
    if campaign.get('config') and campaign['config'] != f'{campaign["tool"]}.php':
        cmd += f' --config={campaign["config"]}'
    return cmd


def applied_rules(entry: dict) -> list[str]:
    rules = entry.get('applied_rectors') or entry.get('applied_rules') or []
    # Fractor prints changelog lines instead of classes with --show-changelog: keep classes only.
    return [r for r in rules if '\\' in r]


def run_json(flight: Flight, cmd: str, log_name: str) -> dict:
    rc, out, err, log = flight.run_runtime(cmd, log_name=log_name, merge=False)
    data = extract_json(out)
    if data is None:
        print(out[-4000:] + err[-4000:])
        die(f'no JSON from: {cmd} (exit {rc}). Log: {flight.rel(log)}')
    if data.get('errors'):
        print('tool reported errors:')
        for error in data['errors']:
            print(f'  {error.get("file")}:{error.get("line", "")} {error.get("message")}')
    data['_log'] = flight.rel(log)
    return data


def rule_order(flight: Flight, campaign: dict) -> list[str]:
    """Registration order approximates the order in which the tool applies rules."""
    if campaign['tool'] != 'rector':
        return []
    cmd = f'{flight.tool("rector")} list-rules --output-format=json'
    if campaign.get('config') and campaign['config'] != 'rector.php':
        cmd += f' --config={campaign["config"]}'
    rc, out, _, _ = flight.run_runtime(cmd, merge=False)
    start = out.find('[') if out.find('[') != -1 and (out.find('{') == -1 or out.find('[') < out.find('{')) else -1
    data = None
    if start != -1:
        import json
        try:
            data = json.loads(out[start:out.rfind(']') + 1])
        except ValueError:
            data = None
    if data is None:
        data = extract_json(out)
    if isinstance(data, dict):
        data = data.get('rules') or data.get('rectors') or []
    if isinstance(data, dict):
        # PHP arrays with gaps (after array_unique) serialise as objects with numeric keys.
        data = [value for _, value in sorted(data.items(), key=lambda kv: int(kv[0]) if str(kv[0]).isdigit() else 0)]
    return [r for r in (data or []) if isinstance(r, str) and '\\' in r]


def rule_source(flight: Flight, fqcn: str) -> dict:
    """File and @changelog references of a rule, read from the installed tool."""
    short = short_class(fqcn)
    namespace = fqcn.rsplit('\\', 1)[0] if '\\' in fqcn else ''
    search = ' '.join(d for d in ('vendor/ssch', 'vendor/a9f', 'vendor/rector/rector/rules', 'vendor/rector/rector/src')
                      if (flight.root / d).is_dir())
    if not search:
        return {}
    rc, out, _ = sh(f"grep -rlE --include='{short}.php' '^(final |abstract )*class {short}\\b' {search}", flight.root, merge=False)
    for candidate in out.splitlines():
        text = (flight.root / candidate).read_text(encoding='utf-8', errors='replace')
        if namespace and f'namespace {namespace};' not in text:
            continue
        return {'file': candidate, 'changelog': re.findall(r'@changelog\s+(\S+)', text)}
    return {}


def supports_only(flight: Flight, campaign: dict) -> bool:
    if 'only_supported' not in campaign:
        rc, out, _, _ = flight.run_runtime(f'{flight.tool(campaign["tool"])} process --help')
        campaign['only_supported'] = '--only' in out
    return campaign['only_supported']


# -- commands --------------------------------------------------------------------

def cmd_plan(args) -> None:
    flight = Flight.load()
    tool = args.tool or 'rector'
    name = args.campaign or default_campaign(flight, tool)
    campaign = campaign_of(flight, name, create_tool=tool)
    if args.config:
        campaign['config'] = args.config
    if not (flight.root / campaign['config']).is_file():
        die(f'{campaign["config"]} not found. Create it: upgrade-pilot rules config --tool {campaign["tool"]} --level <major>')
    data = run_json(flight, base_cmd(flight, campaign) + ' --dry-run', f'{name}-plan')
    per_rule: dict[str, list[str]] = {}
    printer_only = []
    for entry in data.get('file_diffs', []):
        if not applied_rules(entry):
            printer_only.append(entry['file'])
        for rule in applied_rules(entry):
            per_rule.setdefault(rule, []).append(entry['file'])
    order = rule_order(flight, campaign)
    if order:
        campaign['registered'] = order
    position = {rule: i for i, rule in enumerate(campaign.get('registered') or [])}
    rules = campaign['rules']
    for rule, files in per_rule.items():
        if rule not in rules:
            rules[rule] = {'status': 'pending', 'first_seen': now(), 'order': position.get(rule, 10000 + len(rules))}
        entry = rules[rule]
        entry['files'] = sorted(set(files))
        if entry['status'] in ('committed',):
            entry['status'] = 'reappeared'
    for rule, entry in rules.items():
        if rule not in per_rule and entry['status'] == 'pending':
            entry['status'] = 'absorbed'
            entry['note'] = (entry.get('note') or '') + ' no longer reported by the dry run'
    campaign['plans'].append({'at': now(), 'commit': git_head(flight.root), 'changed_files': data.get('totals', {}).get('changed_files', 0),
                              'rules': len(per_rule), 'printer_only': printer_only, 'log': data['_log']})
    flight.event(f'{name}: plan -> {len(per_rule)} rules over {data.get("totals", {}).get("changed_files", 0)} files')
    flight.save()
    open_rules = {r: f for r, f in per_rule.items() if rules[r]['status'] in ('pending', 'reappeared', 'applied')}
    declined = sorted(set(per_rule) - set(open_rules))
    rule_files = {f for files in open_rules.values() for f in files}
    print(f'campaign {name} ({campaign["tool"]}, {campaign["config"]}): {len(open_rules)} open rules would change '
          f'{len(rule_files)} files' + (f', {len(declined)} still reported but decided ({", ".join(rules[r]["status"] for r in declined)})' if declined else ''))
    print_rules(campaign, only_open=not args.all)
    if printer_only:
        print(f'  {len(printer_only)} file(s) differ only by the tool\'s own formatting, no rule attributed: '
              f'{", ".join(printer_only)}. Not part of the campaign. Files a rule does touch get reprinted too, so restore unrelated whitespace in review.')


def print_rules(campaign: dict, only_open: bool = False) -> None:
    rows = sorted(campaign['rules'].items(), key=lambda kv: kv[1].get('order', 99999))
    for rule, entry in rows:
        if only_open and entry['status'] not in ('pending', 'applied', 'reappeared'):
            continue
        files = entry.get('files', [])
        extra = f' commit {entry["commit"]}' if entry.get('commit') else ''
        note = f'  ({entry["note"].strip()})' if entry.get('note') and entry['status'] in ('skipped', 'noop', 'absorbed') else ''
        print(f'  {entry["status"]:<10} {short_class(rule):<60} {len(files):>3} file(s){extra}{note}')


def next_rule(campaign: dict) -> str | None:
    open_rules = [(e.get('order', 99999), r) for r, e in campaign['rules'].items() if e['status'] in ('pending', 'reappeared')]
    return sorted(open_rules)[0][1] if open_rules else None


def cmd_next(args) -> None:
    flight = Flight.load()
    name = args.campaign or default_campaign(flight, args.tool)
    campaign = campaign_of(flight, name)
    applied = [r for r, e in campaign['rules'].items() if e['status'] == 'applied']
    if applied:
        print(f'{applied[0]}\n  status: applied, not committed yet. Review, measure, then rules commit or rules skip.')
        return
    rule = next_rule(campaign)
    if not rule:
        print(f'campaign {name}: nothing pending. Re-run rules plan to confirm the dry run is empty.')
        return
    entry = campaign['rules'][rule]
    print(rule)
    print(f'  files: {", ".join(entry.get("files", []))}')


def resolve_rule(campaign: dict, wanted: str | None, statuses: tuple[str, ...]) -> str:
    candidates = [r for r, e in campaign['rules'].items() if e['status'] in statuses]
    if wanted:
        wanted = wanted.lstrip('\\')
        matches = [r for r in campaign['rules'] if r == wanted or short_class(r) == wanted]
        if not matches:
            die(f'rule {wanted} is not part of this campaign')
        return matches[0]
    if len(candidates) == 1:
        return candidates[0]
    die(f'name the rule with --rule. Candidates: {", ".join(short_class(c) for c in candidates) or "none"}')
    return ''


def cmd_apply(args) -> None:
    flight = Flight.load()
    name = args.campaign or default_campaign(flight, args.tool)
    campaign = campaign_of(flight, name)
    if any(e['status'] == 'applied' for e in campaign['rules'].values()):
        die('another rule is applied and not committed. Commit or skip it first.')
    rule = resolve_rule(campaign, args.rule, ('pending', 'reappeared')) if args.rule else next_rule(campaign)
    if not rule:
        die('nothing pending. Run rules plan.')
    dirty = git_dirty(flight.root)
    if dirty and not args.allow_dirty:
        die('working tree is not clean, so the diff could not be attributed to one rule:\n  ' + '\n  '.join(dirty[:20]))

    cmd = base_cmd(flight, campaign)
    if campaign['tool'] == 'fractor' or supports_only(flight, campaign):
        cmd += f" --only='{rule}'"
    else:
        registered = campaign.get('registered') or rule_order(flight, campaign)
        if rule not in registered:
            die(f'{rule} is not in list-rules output, cannot build a single-rule configuration')
        wrapper = flight.dir / 'tmp' / 'rector-only.php'
        wrapper.parent.mkdir(parents=True, exist_ok=True)
        project = f"__DIR__ . '/../../{campaign['config']}'"
        skip = '[\n        ' + ',\n        '.join(f"'{r.replace(chr(92), chr(92) * 2)}'" for r in registered if r != rule) + ',\n    ]'
        wrapper.write_text(WRAPPER_TEMPLATE.format(project=project, skip=skip), encoding='utf-8')
        cmd = cmd.split(' --config=')[0] + f' --config={flight.rel(wrapper)}'
    data = run_json(flight, cmd, f'{name}-apply-{short_class(rule)}')

    changed = sorted({e['file'] for e in data.get('file_diffs', [])} | {Path(f).as_posix() for f in data.get('changed_files', [])})
    status_lines = git_dirty(flight.root)
    new_files = [line[3:] for line in status_lines if line.startswith('??')]
    touched = [line[3:] for line in status_lines]
    others = sorted({r for e in data.get('file_diffs', []) for r in applied_rules(e)} - {rule})
    markers = []
    diff = git(flight.root, 'diff', '-U0')
    for line in diff.splitlines():
        if line.startswith('+') and not line.startswith('+++') and MARKERS.search(line):
            markers.append(line[1:].strip())
    for new in new_files:
        path = flight.root / new
        if path.is_file():
            for number, line in enumerate(path.read_text(encoding='utf-8', errors='replace').splitlines(), 1):
                if MARKERS.search(line):
                    markers.append(f'{new}:{number}: {line.strip()}')

    entry = campaign['rules'][rule]
    if not touched:
        entry.update({'status': 'noop', 'at': now(), 'note': 'changes nothing when applied alone'})
        flight.event(f'{name}: {short_class(rule)} is a no-op alone')
        flight.save()
        print(f'{short_class(rule)}: no change when applied alone -> marked noop. Next: rules plan')
        return
    source = rule_source(flight, rule)
    entry.update({'status': 'applied', 'applied_at': now(), 'changed': touched, 'new_files': new_files,
                  'markers': markers, 'co_applied': others, 'log': data['_log'],
                  'source': source.get('file'), 'changelog': source.get('changelog', [])})
    flight.event(f'{name}: applied {short_class(rule)} -> {len(touched)} file(s)' + (f', {len(new_files)} new' if new_files else '')
                 + (f', {len(markers)} marker(s)' if markers else ''))
    flight.save()
    print(f'applied {rule}')
    print(f'  changed: {", ".join(touched)}')
    if source.get('file'):
        print(f'  rule source: {source["file"]}')
    for link in source.get('changelog', []):
        print(f'  changelog: {link}')
    if others:
        print(f'  ALSO applied by the tool in the same run: {", ".join(short_class(o) for o in others)}')
    if new_files:
        print(f'  NEW FILES (generated code, read before trusting): {", ".join(new_files)}')
    if markers:
        print('  MARKERS in added code (unfinished work the tool left for you):')
        for marker in markers:
            print(f'    {marker}')
    print('  next: review the diff, run the suites, then rules commit (or rules skip --reason)')


def cmd_commit(args) -> None:
    flight = Flight.load()
    name = args.campaign or default_campaign(flight, args.tool)
    campaign = campaign_of(flight, name)
    rule = resolve_rule(campaign, args.rule, ('applied',))
    entry = campaign['rules'][rule]
    if entry['status'] != 'applied':
        die(f'{short_class(rule)} is {entry["status"]}, not applied')
    if not git_dirty(flight.root):
        die('nothing to commit')
    from .commit import create_commit, read_body
    body = read_body(args)
    marker = f'Applied {campaign["tool"].capitalize()} rule {rule}.'
    if rule not in body:
        body = (body.rstrip() + '\n\n' + marker).strip()
    sha = create_commit(flight, args.tag, args.subject, body, args.step or name, args.step_title or f'{name}: {campaign["tool"]} rules',
                        args.related or [], args.breaking)
    sha = (sha or '')[:10]
    measured = [m['label'] for m in flight.log.get('measurements', []) if m['at'] >= entry.get('applied_at', '')]
    entry.update({'status': 'committed', 'commit': sha, 'committed_at': now(), 'measured': sorted(set(measured))})
    if args.note:
        entry['note'] = args.note
    flight.event(f'{name}: committed {short_class(rule)} as {sha}')
    flight.save()
    print(f'{short_class(rule)} committed as {sha}' + ('' if measured else '  (no measurement since apply!)'))
    print('  next: rules plan (rules interact, the next dry run can differ)')


def cmd_skip(args) -> None:
    flight = Flight.load()
    name = args.campaign or default_campaign(flight, args.tool)
    campaign = campaign_of(flight, name)
    rule = resolve_rule(campaign, args.rule, ('applied', 'pending', 'reappeared'))
    entry = campaign['rules'][rule]
    if entry['status'] == 'applied':
        tracked = [f for f in entry.get('changed', []) if f not in entry.get('new_files', [])]
        if tracked:
            sh('git checkout -- ' + ' '.join(f"'{f}'" for f in tracked), flight.root)
        for new in entry.get('new_files', []):
            path = flight.root / new
            if path.is_file():
                path.unlink()
    entry.update({'status': 'skipped', 'note': args.reason, 'at': now()})
    flight.event(f'{name}: skipped {short_class(rule)}: {args.reason}')
    flight.save()
    print(f'{short_class(rule)} skipped. Remember it on the MEL or QRH if the change is still needed.')


def cmd_list(args) -> None:
    flight = Flight.load()
    names = [args.campaign] if args.campaign else list(flight.log.get('campaigns', {}))
    for name in names:
        campaign = campaign_of(flight, name)
        print(f'campaign {name} ({campaign["tool"]}, {campaign["config"]})')
        print_rules(campaign)
